__all__ = (
    'DEFAULT_PRIORITY', 'INPUT_EVENTS',
)

import pygame.constants as C


DEFAULT_PRIORITY = 0
INPUT_EVENTS = {
    C.KEYDOWN, C.KEYUP,
    C.MOUSEMOTION, C.MOUSEBUTTONDOWN, C.MOUSEBUTTONUP, C.MOUSEWHEEL,
    C.FINGERDOWN, C.FINGERUP, C.FINGERMOTION,
    C.JOYAXISMOTION, C.JOYBALLMOTION, C.JOYHATMOTION, C.JOYBUTTONDOWN, C.JOYBUTTONUP,
}
