__all__ = (
    'INPUT_EVENTS',
)

import pygame.constants as C


INPUT_EVENTS = {
    C.KEYDOWN, C.KEYUP,
    C.MOUSEMOTION, C.MOUSEBUTTONDOWN, C.MOUSEBUTTONUP, C.MOUSEWHEEL,
    C.FINGERDOWN, C.FINGERUP, C.FINGERMOTION,
    C.JOYAXISMOTION, C.JOYBALLMOTION, C.JOYHATMOTION, C.JOYBUTTONDOWN, C.JOYBUTTONUP,
    C.TEXTEDITING, C.TEXTINPUT,
    C.MULTIGESTURE,
}
